### ISSUE TITLE
Colour maps apply to all channels

### ISSUE THREAD

**Issue by 09williamsad** [MochiesCode/Mochies-Unity-Shaders#1]
In the latest version RGBA colour maps apply to all channels instead of the specified channel.
Comparison image between current Uber Shader 1.9 (top) and current (bottom).
![Colour map comparison](https://user-images.githubusercontent.com/23011550/98598930-1a52a600-22d3-11eb-8762-297c227f0824.png)

Zipped unity package containing Uber 1.9 and example model
[Mochies working colour maps.zip](https://github.com/MochiesCode/Mochies-Unity-Shaders/files/5513411/Mochies.working.colour.maps.zip)

Troubleshooting tried:
Changing shader config to standard
Full 1.8
Full 1.7
Full 1.6
New unity project
Restarting unity

**Comment by MochiesCode** [comment]
Issue resolved in 1.8.1 package release.
