### ISSUE TITLE
[Feature Request] VPM/VCC compatibility

### ISSUE THREAD

**Issue by Realmlist** [MochiesCode/Mochies-Unity-Shaders#12]
Please allow us to add this repo in VCC so we can always stay up-to-date with one button press. 🙏

Docs: https://github.com/vrchat-community/template-package/blob/main/README.md

**Comment by MochiesCode** [comment]
This wont be happening for now as it will significantly complicate the process for releasing separate free/patreon packages.

**Comment by AraHaan** [comment]
Question, is there a way to determine if files I am using is the free or paid versions of the package? Or could I try to see if importing one over the other would change anything?

**Comment by AraHaan** [comment]
@MochiesCode would it be fine if someone like say me for example were to manually download the releases from github and then manually import them into a vpm project to export as a vpm package for vcc to consume with a VCC package of mine that depends on it? I figured I should ask here before I actually do it and simply just redirect the people that use that package to this github if they want *faster* updates in real time as there may be some delay in the updates to it vs the github releases page 😂.
