### ISSUE TITLE
Mochie/Standard Shader is broken

### ISSUE THREAD

**Issue by duhdire** [MochiesCode/Mochies-Unity-Shaders#13]
Absolutely no clue how this happened, but there is an issue with the Mochie/Standard material that just fails to load any of its properties, while still having its textures.

Error in console:
ArgumentException: Could not find MaterialProperty: '_TintReflShad', Num properties: 148
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties, System.Boolean propertyIsMandatory) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties) (at <a259d3c004024353a2c217da97495055>:0)
MochieStandardGUI.FindProperties (UnityEditor.MaterialProperty[] props, UnityEngine.Material mat) (at Assets/Mochie/Unity/Editor/MochieStandardGUI.cs:373)
MochieStandardGUI.OnGUI (UnityEditor.MaterialEditor materialEditor, UnityEditor.MaterialProperty[] props) (at Assets/Mochie/Unity/Editor/MochieStandardGUI.cs:426)
UnityEditor.MaterialEditor.PropertiesGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.MaterialEditor.OnInspectorGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

![image](https://github.com/MochiesCode/Mochies-Unity-Shaders/assets/138962419/b429238c-8cc0-4a91-8847-4a358802be12)

**Comment by cutesthypnotist** [comment]
The Editor is probably caching an older version of the shader. I suggest the following steps:

1. Delete Mochie folder, restart editor, then re-import the latest package.
2. Delete the Library and/or package cache folder and then reopen your project.
