### ISSUE TITLE
Found this. I'm sure I'm missing some context

### ISSUE THREAD

**Issue by andybak** [MochiesCode/Mochies-Unity-Shaders#2]
Readme is empty.

I presume you've got some info elsewhere on the web. Link to your blog/YT channel etc?

**Comment by MochiesCode** [comment]
Hi, sorry, I'm not well-versed in the ways of markdown (or github in general) so I haven't attempted making a readme yet. This shader package is generally aimed towards creators within the VRChat community, and any real discussion surrounding it happens in my discord patreon server or DM's. If you'd like some help using it or just have questions, feel free to add me there (Mochie#8794) and I can go over anything you'd like :)
