### ISSUE TITLE
LTCGI Broken with Mochi Standard

### ISSUE THREAD

**Issue by Hayden-Fluff** [MochiesCode/Mochies-Unity-Shaders#20]
# Problem
When enabling LTCGI with Mochi Standard the shader breaks and gives a compile error stating
`Shader error in 'Mochie/Standard': Couldn't open include file '/Packages/at.pimaker.ltcgi/Shaders/LTCGI.cginc'. at Assets/Mochie/Standard Shader/MochieStandardlnput.cginc(23)`

This results in LTCGI being unusable with Mochi Standard

# Solution
I edited the MochiStandardInclud.cginc at line 24 to replace
`#include "/Packages/at.pimaker.ltcgi/Shaders/LTCGI.cginc"`
with
`#include "Packages/at.pimaker.ltcgi/Shaders/LTCGI.cginc"`
Removing the `/` before `Packages`, and this fixes the issue.

This also assumes that LTCGI was imported with VCC, as importing it via the git url using UPM, it does not go to that directory.

**Comment by MochiesCode** [comment]
Fixed for next patch. As of now I just require the VCC version as the non-VPM version has other issues with compilation.
