### ISSUE TITLE
Mochie Uber is missing smoothness and packed detail workflow compared to Mochie Standard

### ISSUE THREAD

**Issue by Saberpeep** [MochiesCode/Mochies-Unity-Shaders#21]
After switching one of my materials from Mochie Standard to Mochie Uber hoping for more granular control I found that its not possible to get 1-1 conversion. 

Features missing from Uber that are present in Standard:
1. No option to swap roughness/smoothness.
2. No option to use a packed map in the detail section ("workflow" dropdown is missing)

**Comment by MochiesCode** [comment]
These shaders aren't meant to be a 1-1 conversion of each other. One is for avatars and one is for worlds. I do plan to add a smoothness toggle to uber, but the detail workflow options is too many extra keywords for an already keyword-heavy shader.
