### ISSUE TITLE
Issue when using "packed" workflow instead of metallic workflow

### ISSUE THREAD

**Issue by RavenTheSergal** [MochiesCode/Mochies-Unity-Shaders#23]
when enabling the packed workflow, shadows do not properly work with height maps. in metallic workflow the shadows follow extremely offset heightmaps perfectly, however, in packed workflow, they stay where they would as if there was no height map at all

**Comment by RavenTheSergal** [comment]
correction it appears to be the metallic map doing that

**Comment by RavenTheSergal** [comment]
For context, i've bastardized a height map to give an avatars eyes a "picture looking at you" effect, so my heightmap offset value it extreme negative despite it being made to be used at 0 (to give it a large parallax, the "looking" effect, however i do use normal heightmaps across the rest of the model and the issue persists,

the issue simply being that in packed mode the metallic map does not follow the parallax offset of the heightmap.

**Comment by MochiesCode** [comment]
In which shader?

**Comment by MochiesCode** [comment]
Found this bug in uber shader, fixed for next update.

**Comment by RavenTheSergal** [comment]
yeah uber sorry forgot its a whole pack of shaders lol, thank you so much, i love working with your shader! i find it works the best with heightmaps in comparison to all others
