### ISSUE TITLE
uber shader workflow change leading to Inflated uncompressed filesize

### ISSUE THREAD

**Issue by RavenTheSergal** [MochiesCode/Mochies-Unity-Shaders#24]
in uber shader, switching from metallic to packed does not remove any previously assigned texture maps in metallic workflow during upload using packed, leading to having to upload all maps unless manually fixed, and the upload size in turn being huge.

**Comment by MochiesCode** [comment]
This is just how unity works, the UI is entirely cosmetic. If you want to see what's actually saved in a material you can go into debug mode in the inspector and browse through the saved properties. Some shaders have built functionality to compensate for this behaviour, and it's on my list, but isn't high priority.
