### ISSUE TITLE
Is it possible to exclude only VR from the SSRR function?

### ISSUE THREAD

**Issue by MintakaSeiran** [MochiesCode/Mochies-Unity-Shaders#25]
We are always happy to use it. Thank you.
When implementing real-time reflection on water, ground or objects, the load is known on desktop and mobile, but it becomes very high when used in VR.

Is it therefore possible to set a setting to exclude VR mode only? Or I would like to be able to select it like VRChat Shader Globals.
I hope you will find this useful.

-reference
VRChat Shader Globals
https://creators.vrchat.com/worlds/vrc-graphics/vrchat-shader-globals/

**Comment by MochiesCode** [comment]
I will add a toggle for VR in the next update :)
