### ISSUE TITLE
Mochie v1.4 HDR Issue

### ISSUE THREAD

**Issue by Alucard0504** [MochiesCode/Mochies-Unity-Shaders#4]
On v1.4 when model encounters a screen space shader with HDR or some worlds with similar HDR effects, model turns blinding white

**Comment by MochiesCode** [comment]
Sorry, which shader has this issue? None of them are on version 1.4. Also could you provide an example of a world where this happens so I can test?

**Comment by Alucard0504** [comment]
I was in the light box. And it is the Uber Shader in the v1.4 package. I was using HDR on a screen space shader. Did the same in unity and in game. Removeing HDR option from scene camera makes the blinding white issue stop. Seems something odd with lighting again

**Comment by MochiesCode** [comment]
I assume you mean 1.14, but what is this "HDR on a screen space shader" you're referring to? I know for a fact there's nothing wrong with the lighting code right now, it's been tested extensively under conditions very similar to silent's light box. If you'd like me to look into this further you'll need to provide a copy of all your material settings used with Uber, and if it's the HDR in my screenspace shader, the settings on that too. If this is a result of someone else' screenspace shader mucking with the lighting in my Uber shader, however, that's out of my hands and you'll need to contact them to fix it.

**Comment by Alucard0504** [comment]
Dont mind this one. It seems like my unity project was dying... Today it just crashed and throws a bunch of errors. Welp. looks like its unity just being unity

**Comment by Alucard0504** [comment]
shader works fine in a new project

**Comment by Alucard0504** [comment]
[](url)
![image](https://user-images.githubusercontent.com/67936173/120054754-796dd300-bff7-11eb-9f11-36005c89ce6c.png)

NVM, this is what happens

**Comment by Alucard0504** [comment]
It still happens with the ubershader in v1.4

**Comment by MochiesCode** [comment]
As I previously stated: 

"If you'd like me to look into this further you'll need to provide a copy of all your material settings used with Uber".

And there is no v1.4, it's v1.14, please refer to it as such to avoid confusing future readers.

**Comment by Alucard0504** [comment]
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!21 &2100000
Material:
  serializedVersion: 6
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: Body 1
  m_Shader: {fileID: 4800000, guid: b252ff402bce931488cf8ff5152bf2dc, type: 3}
  m_ShaderKeywords: GEOM_TYPE_FROND VIGNETTE_MASKED _ALPHATEST_ON _COLORADDSUBDIFF_ON
    _COLORCOLOR_ON _EMISSION _NORMALMAP
  m_LightmapFlags: 1
  m_EnableInstancingVariants: 0
  m_DoubleSidedGI: 0
  m_CustomRenderQueue: 2450
  stringTagMap:
    RenderType: TransparentCutout
  disabledShaderPasses:
  - ALWAYS
  m_SavedProperties:
    serializedVersion: 3
    m_TexEnvs:
    - _AOTintTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _AlphaMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _BCNoiseTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _BumpMap:
        m_Texture: {fileID: 2800000, guid: f690d80c31da9a740a4a26934234dbd9, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Cube:
        m_Texture: {fileID: 8900000, guid: c1149cb0fa162f34985e8b9ceb63e552, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _CubeBlendMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailAlbedoMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailNormalMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailOcclusionMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DetailRoughnessMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DiffuseMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DissolveFlow:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DissolveMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DissolveRimTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DissolveTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DistortUVMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _DistortUVMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ERimMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ERimTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _EmissMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _EmissionMap:
        m_Texture: {fileID: 2800000, guid: d4291de5a7886924ba74e211e3227dd1, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _FilterMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Flipbook0:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Flipbook1:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _InterpMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MainTex:
        m_Texture: {fileID: 2800000, guid: a907647f3c42b5246bc10319fb553289, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MainTex2:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MainTexCube0:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Matcap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Matcap1:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MatcapBlendMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MatcapMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MetallicGlossMap:
        m_Texture: {fileID: 2800000, guid: f32d950962c7078489458d881fc556ed, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MirrorTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _NearClipMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _NoiseTexSSR:
        m_Texture: {fileID: 2800000, guid: b7359cc7e3e84444b88656ff6c166220, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _OcclusionMap:
        m_Texture: {fileID: 2800000, guid: 8e7f1a3079473dc4f841c7599eb3b9f7, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _OutlineMask:
        m_Texture: {fileID: 2800000, guid: 651eda19f40ce0240bd119da3e0cfd01, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _OutlineTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _PackedMap:
        m_Texture: {fileID: 2800000, guid: 7bf6e7da025d3fe49a97d2b9532c2660, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _PackedMask0:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _PackedMask1:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _PackedMask2:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _PackedMask3:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ParallaxMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _PulseMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ReflCube:
        m_Texture: {fileID: 8900000, guid: e3195af7e5fb6324cacf5f076f29009c, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ReflectionMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _RefractionDissolveMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _RefractionMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _RimMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _RimTex:
        m_Texture: {fileID: 2800000, guid: 1cf9225ccbc5d304790db25b05b1be2a, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ShadowMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ShadowRamp:
        m_Texture: {fileID: 2800000, guid: 784e54997d040484c80f2230c8b5c0e6, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _SmoothnessMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _SpecGlossMap:
        m_Texture: {fileID: 2800000, guid: ed3e83576f4184f4984ea3ea80adca1e, type: 3}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _SpecularMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Spritesheet:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Spritesheet1:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _SubsurfaceMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _SubsurfaceTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _TeamColorMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _TranslucencyMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _VertexExpansionMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _VertexRoundingMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    m_Floats:
    - _AOContrast: 1
    - _AOFiltering: 0
    - _AOIntensity: 0
    - _AOLightness: 0
    - _ATM: 0
    - _AdvancedChannels: 0
    - _Alpha: 1
    - _AlphaMaskChannel: 0
    - _AnisoAngleX: 1
    - _AnisoAngleY: 1
    - _AnisoLayerStr: 0.1
    - _AnisoLayerX: 1
    - _AnisoLayerY: 1
    - _AnisoLerp: 0
    - _AnisoSteps: 2
    - _AnisoStr: 1
    - _ApplyAlbedoTint: 0
    - _ApplyOutlineEmiss: 0
    - _ApplyOutlineLighting: 0
    - _AttenSmoothing: 1
    - _AudioLinkBCDissolveBand: 0
    - _AudioLinkBCDissolveMultiplier: 0
    - _AudioLinkDissolveBand: 0
    - _AudioLinkDissolveMultiplier: 0
    - _AudioLinkEmissionBand: 0
    - _AudioLinkEmissionMultiplier: 0
    - _AudioLinkPreview: 0
    - _AudioLinkRimBand: 0
    - _AudioLinkRimMultiplier: 0
    - _AudioLinkRimPulse: 0
    - _AudioLinkRimPulseSharp: 0.3
    - _AudioLinkRimPulseWidth: 0.5
    - _AudioLinkRimWidth: 0
    - _AudioLinkToggle: 0
    - _AudioLinkVertManipBand: 0
    - _AudioLinkVertManipMultiplier: 0
    - _AutoRotate0: 0
    - _AutoShift: 0
    - _AutoShiftSpeed: 0.25
    - _BCDissolveStr: 0
    - _BCDissolveToggle: 0
    - _BCRimWidth: 0.5
    - _BlendMode: 1
    - _Brightness: 1
    - _BumpScale: 1
    - _ClampAdditive: 1
    - _ClearCoat: 0
    - _ClipRimStr: 1
    - _ClipRimWidth: 1
    - _ClonePattern: 0
    - _CloneToggle: 0
    - _ColorPreservation: 1
    - _Contrast: 1
    - _CrossMode: 0
    - _Crossfade: 0.2
    - _CubeBlend: 0
    - _CubeBlendMode: 0
    - _CubeMode: 0
    - _Cull: 2
    - _CullingMode: 2
    - _Cutoff: 0.5
    - _DFClones: 0
    - _DebugEnum: 0
    - _DebugFloat: 1
    - _DebugIntRange: 1
    - _DebugRange: 1
    - _DebugToggle: 0
    - _DetailAlbedoBlending: 1
    - _DetailAlbedoStrength: 1
    - _DetailNormalMapScale: 0.49
    - _DetailOcclusionBlending: 3
    - _DetailOcclusionStrength: 1
    - _DetailRoughBlending: 4
    - _DetailRoughStrength: 1
    - _DirectAO: 1
    - _DirectCont: 0.6
    - _DisneyDiffuse: 0
    - _DissolveAmount: 0
    - _DissolveBlendSpeed: 0.2
    - _DissolveBlending: 0
    - _DissolveClones: 0
    - _DissolveRimWidth: 0.5
    - _DissolveStyle: 0
    - _DistanceFadeMax: 4
    - _DistanceFadeMin: 2
    - _DistanceFadeToggle: 0
    - _DistortDetailUV: 0
    - _DistortEmissUV: 0
    - _DistortMainUV: 0
    - _DistortMatcap0: 0
    - _DistortMatcap1: 0
    - _DistortRimUV: 0
    - _DistortUVStr: 1
    - _DistortUVs: 0
    - _DistortionStyle: 0
    - _Dith: 0
    - _DitheredShadows: 0
    - _DstBlend: 0
    - _ERimBlending: 1
    - _ERimEdge: 0
    - _ERimRoughness: 0.5
    - _ERimStr: 1
    - _ERimUseRough: 0
    - _ERimWidth: 0.7
    - _EdgeFade: 0.327
    - _EmissIntensity: 1
    - _EmissionToggle: 1
    - _EnableMaskTransform: 0
    - _EnablePackedHeight: 0
    - _EnableSpritesheet: 0
    - _EnableSpritesheet1: 0
    - _EnvironmentRim: 0
    - _FPS: 30
    - _FPS1: 30
    - _Filtering: 1
    - _GSAA: 0
    - _GeomDissolveAmount: -2
    - _GeomDissolveAxis: 1
    - _GeomDissolveAxisFlip: 0
    - _GeomDissolveClamp: 0
    - _GeomDissolveClip: 0
    - _GeomDissolveFilter: 1
    - _GeomDissolveWidth: 0.25
    - _GeomDissolveWireframe: 0
    - _GlitchClones: 0
    - _GlitchFrequency: 0
    - _GlitchIntensity: 0
    - _GlitchToggle: 0
    - _GlossMapScale: 0.8
    - _Glossiness: 0.5
    - _GlossyReflections: 1
    - _HDR: 0.05
    - _HardenNormals: 0
    - _HeightChannel: 3
    - _HeightContrast: 1
    - _HeightFiltering: 0
    - _HeightIntensity: 0
    - _HeightLightness: 0
    - _Hue: 0
    - _IgnoreFilterMask: 0
    - _IndirectAO: 1
    - _IndirectCont: 0.5
    - _Instability: 0
    - _Invert: 0
    - _IsCubeBlendMask: 0
    - _LRad: 5
    - _LightingBasedIOR: 1
    - _LitRim: 1
    - _MainTexTint: 0
    - _ManualScrub: 0
    - _ManualScrub1: 0
    - _ManualSpecBright: 0
    - _MaskingMode: 1
    - _MatcapBlending: 0
    - _MatcapBlending1: 0
    - _MatcapRough: 0.5
    - _MatcapRough1: 0.5
    - _MatcapStr: 1
    - _MatcapStr1: 1
    - _MatcapToggle: 0
    - _MatcapUseRough: 0
    - _MatcapUseRough1: 0
    - _MaxSteps: 14
    - _Metallic: 0
    - _MetallicChannel: 0
    - _MirrorBehavior: 0
    - _Mode: 0
    - _NaNLmao: 0
    - _NearClip: 0
    - _NearClipToggle: 0
    - _NoiseOctaves: 1
    - _NoiseSpeed: 0.5
    - _NonlinearSHToggle: 1
    - _OcclusionChannel: 2
    - _OcclusionStrength: 1
    - _Outline: 6.34
    - _OutlineColorMix: 0
    - _OutlineCulling: 0
    - _OutlineEnabled: 0
    - _OutlineMult: 1
    - _OutlineRange: 0.2
    - _OutlineStencilCompare: 6
    - _OutlineStencilPass: 0
    - _OutlineThicc: 0.3
    - _OutlineToggle: 0
    - _PBRWorkflow: 0
    - _PackedRoughPreview: 0
    - _Parallax: 0.02
    - _PatternMult: 2.5
    - _PostFiltering: 0
    - _PreviewAO: 0
    - _PreviewHeight: 0
    - _PreviewRough: 0
    - _PreviewSmooth: 0
    - _PulseSpeed: 1
    - _PulseStr: 0.5
    - _PulseToggle: 0
    - _PulseWaveform: 0
    - _RTDirectCont: 1
    - _RTIndirectCont: 1
    - _RTSelfShadow: 1
    - _RampPos: 0
    - _RampSmooth: 1
    - _RampThreshold: 0
    - _RampWeight: 0.3
    - _RampWidth0: 0.3
    - _RampWidth1: 0.5
    - _Range: 10
    - _ReactThresh: 0.4
    - _ReactToggle: 1
    - _RealtimeSpec: 0
    - _ReflCubeFallback: 0
    - _ReflRough: 0.5
    - _ReflStepping: 0
    - _ReflSteps: 7
    - _ReflUseRough: 0
    - _ReflectionStr: 1
    - _Reflections: 1
    - _Refraction: 0
    - _RefractionCA: 0
    - _RefractionCAStr: 0.1
    - _RefractionDissolveMaskStr: 1
    - _RefractionIOR: 1.3
    - _RefractionMaskStr: 1
    - _RefractionOpac: 0
    - _RenderMode: 1
    - _RimBlending: 1
    - _RimEdge: 0
    - _RimLighting: 1
    - _RimMax: 0
    - _RimMin: 0
    - _RimStr: 0.845
    - _RimWidth: 0.95
    - _RippleAmplitude: 1
    - _RippleContinuity: 1
    - _RippleFrequency: 0
    - _RippleInvert: 1
    - _RippleStrength: 0
    - _RoughContrast: 0.52
    - _RoughIntensity: 0.1
    - _RoughLightness: 0.1
    - _RoughnessChannel: 3
    - _RoughnessFiltering: 1
    - _SAtten: 0.8
    - _SHStr: 0
    - _SPen: 0.5
    - _SRad: 5
    - _SSR: 0
    - _SSharp: 0.5
    - _SStr: 1
    - _SaturateEP: 1
    - _Saturation: 0.891
    - _Screenspace: 0
    - _ScrubPos: 1
    - _ScrubPos1: 1
    - _ShadowConditions: 0
    - _ShadowDithering: 0
    - _ShadowMode: 2
    - _ShadowStr: 1
    - _ShadowToggle: 0
    - _SharpSpecStr: 1
    - _SharpSpecular: 0
    - _ShatterClones: 0
    - _ShatterCull: 0.535
    - _ShatterMax: 0.65
    - _ShatterMin: 0.25
    - _ShatterSpread: 0.347
    - _ShatterToggle: 0
    - _SmoothContrast: 1
    - _SmoothIntensity: 0
    - _SmoothLightness: 0
    - _SmoothnessFiltering: 0
    - _SmoothnessTextureChannel: 0
    - _SpecBiasOverride: 0.5
    - _SpecBiasOverrideToggle: 0
    - _SpecRough: 0.5
    - _SpecStr: 1
    - _SpecUseRough: 0
    - _Specular: 1
    - _SpecularHighlights: 1
    - _SpritesheetBlending: 2
    - _SpritesheetBlending1: 2
    - _SpritesheetBrightness: 1
    - _SpritesheetBrightness1: 1
    - _SpritesheetMode0: 0
    - _SpritesheetMode1: 0
    - _SpritesheetRot: 0
    - _SpritesheetRot1: 0
    - _SrcBlend: 1
    - _StaticLightDirToggle: 0
    - _Stencil: 0
    - _StencilCompare: 8
    - _StencilFail: 0
    - _StencilPass: 2
    - _StencilRef: 1
    - _StencilToggle: 1
    - _StencilZFail: 0
    - _Step: 0.1
    - _StylizeRamp: 1
    - _StylizeRim: 1
    - _StylizeSpecular: 0
    - _Subsurface: 0
    - _TeamFiltering: 0
    - _UVAniso: 0
    - _UVSec: 0
    - _UnlitMatcap: 0
    - _UnlitMatcap1: 0
    - _UnlitRefraction: 0
    - _UnlitRim: 1
    - _UnlitSpritesheet: 0
    - _UnlitSpritesheet1: 0
    - _UseAlphaMask: 0
    - _UseCurvature: 0
    - _UseMatcap1: 0
    - _UseMetallicMap: 1
    - _UseProbe: 1
    - _UseSmoothMap: 0
    - _UseSpecMap: 1
    - _UseSpritesheetAlpha: 0
    - _UseVertexColor: 0
    - _UsingDetailAlbedo: 0
    - _UsingDetailOcclusion: 0
    - _UsingDetailRough: 0
    - _VLightCont: 1
    - _Value: 0
    - _VertexExpansionClamp: 0
    - _VertexManipulationToggle: 0
    - _VertexRounding: 0
    - _VertexRoundingPrecision: 100
    - _Visibility: 0
    - _WFClones: 0
    - _WFFill: 0
    - _WFMode: 0
    - _WFVisibility: 1
    - _WireframeToggle: 0
    - _ZTest: 4
    - _ZWrite: 1
    - _glossChannel: 3
    - _heightChannel: 1
    - _maskChannel: 3
    - _metallicChannel: 0
    - _occlusionChannel: 1
    - _specularBrightness: 1
    m_Colors:
    - _AOTint: {r: 0, g: 0, b: 0, a: 1}
    - _BCColor: {r: 1, g: 1, b: 1, a: 1}
    - _BCRimCol: {r: 1, g: 1, b: 1, a: 1}
    - _ClipRimColor: {r: 1, g: 1, b: 1, a: 1}
    - _Clone1: {r: 1, g: 0, b: 0, a: 1}
    - _Clone2: {r: -1, g: 0, b: 0, a: 1}
    - _Clone3: {r: 0, g: 0, b: 1, a: 1}
    - _Clone4: {r: 0, g: 0, b: -1, a: 1}
    - _Clone5: {r: 0.5, g: 0, b: 0.5, a: 1}
    - _Clone6: {r: -0.5, g: 0, b: 0.5, a: 1}
    - _Clone7: {r: 0.5, g: 0, b: -0.5, a: 1}
    - _Clone8: {r: -0.5, g: 0, b: -0.5, a: 1}
    - _Color: {r: 1, g: 1, b: 1, a: 1}
    - _CubeColor0: {r: 1, g: 1, b: 1, a: 1}
    - _CubeRotate0: {r: 180, g: 0, b: 0, a: 0}
    - _DebugColor: {r: 1, g: 1, b: 1, a: 1}
    - _DebugHDRColor: {r: 1, g: 1, b: 1, a: 1}
    - _DebugVector: {r: 0, g: 0, b: 0, a: 0}
    - _DetColor: {r: 1, g: 1, b: 1, a: 1}
    - _DetailMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _DetailScroll: {r: 0, g: 0, b: 0, a: 0}
    - _DiffuseMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _DissolveNoiseScale: {r: 10, g: 10, b: 10, a: 0}
    - _DissolvePoint0: {r: 0, g: 0, b: 0, a: 0}
    - _DissolvePoint1: {r: 1, g: 1, b: 1, a: 1}
    - _DissolveRimCol: {r: 1, g: 1, b: 1, a: 1}
    - _DissolveScroll0: {r: 0, g: 0, b: 0, a: 0}
    - _DissolveScroll1: {r: 0, g: 0, b: 0, a: 0}
    - _DistortUVScroll: {r: 0, g: 0, b: 0, a: 0}
    - _ERimMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _ERimScroll: {r: 0, g: 0, b: 0, a: 0}
    - _ERimTint: {r: 1, g: 1, b: 1, a: 1}
    - _EmissMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _EmissPulseMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _EmissScroll: {r: 0, g: 0, b: 0, a: 0}
    - _EmissionColor: {r: 1.4980392, g: 0.57254905, b: 0.20392157, a: 1}
    - _EntryPos: {r: 0, g: 1, b: 0, a: 0}
    - _FakeLight: {r: 0, g: 0.5, b: 1, a: 1}
    - _FilterMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _FrameClipOfs: {r: 0, g: 0, b: 0, a: 0}
    - _FrameClipOfs1: {r: 0, g: 0, b: 0, a: 0}
    - _GeomDissolveSpread: {r: 0.1, g: 0.1, b: 0.1, a: 1}
    - _InterpMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _MainTexScroll: {r: 0, g: 0, b: 0, a: 0}
    - _MatcapBlendMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _MatcapColor: {r: 1, g: 1, b: 1, a: 1}
    - _MatcapColor1: {r: 1, g: 1, b: 1, a: 1}
    - _MatcapMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _NoiseScale: {r: 1, g: 1, b: 0, a: 0}
    - _OutlineCol: {r: 1.7411011, g: 0.6632725, b: 0.23504864, a: 1}
    - _OutlineColor: {r: 0, g: 0, b: 0, a: 1}
    - _OutlineMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _OutlineScroll: {r: 0, g: 0, b: 0, a: 0}
    - _Position: {r: 0, g: 0, b: 0.25, a: 0}
    - _RGB: {r: 1, g: 1, b: 1, a: 0}
    - _ReflCol: {r: 1, g: 1, b: 1, a: 1}
    - _ReflectionMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _RefractionDissolveMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _RefractionMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _RefractionTint: {r: 1, g: 1, b: 1, a: 1}
    - _RimCol: {r: 1.4980392, g: 0.57254905, b: 0.20392157, a: 1}
    - _RimMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _RimScroll: {r: 0, g: 0, b: 0, a: 0}
    - _RippleSeeds: {r: 5.213, g: 8.7622, b: 12.9, a: 0}
    - _Rotation: {r: 0, g: 0, b: 0, a: 0}
    - _RowsColumns: {r: 8, g: 8, b: 0, a: 0}
    - _RowsColumns1: {r: 8, g: 8, b: 0, a: 0}
    - _SColor: {r: 1, g: 1, b: 1, a: 1}
    - _ShadowColor: {r: 1, g: 1, b: 1, a: 1}
    - _ShadowMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _ShadowTint: {r: 0, g: 0, b: 0, a: 1}
    - _SpecCol: {r: 1, g: 1, b: 1, a: 1}
    - _SpecularMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _SpritesheetCol: {r: 1, g: 1, b: 1, a: 1}
    - _SpritesheetCol1: {r: 1, g: 1, b: 1, a: 1}
    - _SpritesheetPos: {r: 0, g: 0, b: 0, a: 0}
    - _SpritesheetPos1: {r: 0, g: 0, b: 0, a: 0}
    - _SpritesheetScale: {r: 1, g: 1, b: 0, a: 0}
    - _SpritesheetScale1: {r: 1, g: 1, b: 0, a: 0}
    - _StaticLightDir: {r: 0, g: 0.75, b: 1, a: 0}
    - _SubsurfaceMaskScroll: {r: 0, g: 0, b: 0, a: 0}
    - _TeamColor0: {r: 1, g: 1, b: 1, a: 1}
    - _TeamColor1: {r: 1, g: 1, b: 1, a: 1}
    - _TeamColor2: {r: 1, g: 1, b: 1, a: 1}
    - _TeamColor3: {r: 1, g: 1, b: 1, a: 1}
    - _VertexExpansion: {r: 0, g: 0, b: 0, a: 0}
    - _WFColor: {r: 0, g: 0, b: 0, a: 1}
