### ISSUE TITLE
Water shaders are not translucent v1.19

### ISSUE THREAD

**Issue by Velocity37564** [MochiesCode/Mochies-Unity-Shaders#6]
Water shaders cannot be made semi-transparent.
I use this shader to VRChat world.
It worked fine when I built world a few times, but after resetting it, the semi-transparent part is now displayed in white.
If you have an example of the values to set, please let me know.

**Comment by MochiesCode** [comment]
This is a unity bug that I've only encountered once, and I've never been able to reproduce it. If it happens again I'll do my best to investigate further.
