### ISSUE TITLE
UI appears to be broken

### ISSUE THREAD

**Issue by Commander-Fayne** [MochiesCode/Mochies-Unity-Shaders#7]
![image](https://user-images.githubusercontent.com/97197751/148293778-da6702ec-841b-451d-86c3-ebe6aa42cbec.png)

UI looks like this. Fresh install of VRC version unity, fresh download of 1.22 mochie today. The UI does not appear this way with 1.21. Unity presents this error when any material is opened that is using Mochie as the shader. 

![image](https://user-images.githubusercontent.com/97197751/148293910-cf4c4b7e-a8c0-4aea-b3dd-dc238a222326.png)

**Comment by MochiesCode** [comment]
resolved with the latest release
