### ISSUE TITLE
Water Shader artifact when viewing water from a mirror in VR

### ISSUE THREAD

**Issue by Brotaoski** [MochiesCode/Mochies-Unity-Shaders#8]
Noticed there is a weird artifact in the water shader when looking at the water from the view of a mirror while in VR. Not able to replicate the artifact in desktop.   [Video Preview](https://i.imgur.com/t4wws2C.mp4)

**Comment by MochiesCode** [comment]
Fixed as of this patch, forgot to include in notes though.
